export const defLanguages = [
	{ id: 45, selected: true, name: 'Assembly (NASM 2.14.02)' },
	{ id: 46, selected: true, name: 'Bash (5.0.0)' },
	{ id: 47, selected: true, name: 'Basic (FBC 1.07.1)' },
	{ id: 75, selected: true, name: 'C (Clang 7.0.1)' },
	{ id: 76, selected: true, name: 'C++ (Clang 7.0.1)' },
	{ id: 48, selected: true, name: 'C (GCC 7.4.0)' },
	{ id: 52, selected: true, name: 'C++ (GCC 7.4.0)' },
	{ id: 49, selected: true, name: 'C (GCC 8.3.0)' },
	{ id: 53, selected: true, name: 'C++ (GCC 8.3.0)' },
	{ id: 50, selected: true, name: 'C (GCC 9.2.0)' },
	{ id: 54, selected: true, name: 'C++ (GCC 9.2.0)' },
	{ id: 86, selected: true, name: 'Clojure (1.10.1)' },
	{ id: 51, selected: true, name: 'C# (Mono 6.6.0.161)' },
	{ id: 77, selected: true, name: 'COBOL (GnuCOBOL 2.2)' },
	{ id: 55, selected: true, name: 'Common Lisp (SBCL 2.0.0)' },
	{ id: 56, selected: true, name: 'D (DMD 2.089.1)' },
	{ id: 57, selected: true, name: 'Elixir (1.9.4)' },
	{ id: 58, selected: true, name: 'Erlang (OTP 22.2)' },
	{ id: 44, selected: true, name: 'Executable' },
	{ id: 87, selected: true, name: 'F# (.NET Core SDK 3.1.202)' },
	{ id: 59, selected: true, name: 'Fortran (GFortran 9.2.0)' },
	{ id: 60, selected: true, name: 'Go (1.13.5)' },
	{ id: 88, selected: true, name: 'Groovy (3.0.3)' },
	{ id: 61, selected: true, name: 'Haskell (GHC 8.8.1)' },
	{ id: 62, selected: true, name: 'Java (OpenJDK 13.0.1)' },
	{ id: 63, selected: true, name: 'JavaScript (Node.js 12.14.0)' },
	{ id: 78, selected: true, name: 'Kotlin (1.3.70)' },
	{ id: 64, selected: true, name: 'Lua (5.3.5)' },
	{ id: 89, selected: true, name: 'Multi-file program' },
	{ id: 79, selected: true, name: 'Objective-C (Clang 7.0.1)' },
	{ id: 65, selected: true, name: 'OCaml (4.09.0)' },
	{ id: 66, selected: true, name: 'Octave (5.1.0)' },
	{ id: 67, selected: true, name: 'Pascal (FPC 3.0.4)' },
	{ id: 85, selected: true, name: 'Perl (5.28.1)' },
	{ id: 68, selected: true, name: 'PHP (7.4.1)' },
	{ id: 43, selected: true, name: 'Plain Text' },
	{ id: 69, selected: true, name: 'Prolog (GNU Prolog 1.4.5)' },
	{ id: 70, selected: true, name: 'Python (2.7.17)' },
	{ id: 71, selected: true, name: 'Python (3.8.1)' },
	{ id: 80, selected: true, name: 'R (4.0.0)' },
	{ id: 72, selected: true, name: 'Ruby (2.7.0)' },
	{ id: 73, selected: true, name: 'Rust (1.40.0)' },
	{ id: 81, selected: true, name: 'Scala (2.13.2)' },
	{ id: 82, selected: true, name: 'SQL (SQLite 3.27.2)' },
	{ id: 83, selected: true, name: 'Swift (5.2.3)' },
	{ id: 74, selected: true, name: 'TypeScript (3.7.4)' },
	{ id: 84, selected: true, name: 'Visual Basic.Net (vbnc 0.0.0.5943)' },
]
